#!/usr/bin/env python3
# -*- coding: cp1252 -*-

import pandas as pd

__version__ = '0.1.0'

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='pandas + command line (v%s)'%(__version__))

    parser.add_argument('filename', help="path to file")
    parser.add_argument('command', help="e.g. '.columns', will display the result of the last command")
    args = parser.parse_args()
    
    tqdm_command = ''
    if 'progress_apply' in args.command:
        tqdm_command = 'from tqdm import tqdm; tqdm.pandas();'
    
    command = 'import pandas as pd; import numpy as np;'
    command += '%s print(pd.read_csv("%s")%s)'%(tqdm_command,
                                                args.filename,
                                                args.command)
    exec(command)
